steps:
  - label: ":pytest: Run unit tests"
    commands: "docker-compose run test"
    agents:
      queue: "{{ cookiecutter.buildkite_agent }}"

  - wait

  - label: ":partyparrot: Build package"
    commands: "docker-compose run build"
    branches: "master develop"
    agents:
      queue: "{{ cookiecutter.buildkite_agent }}"
