version: "3.7"
services:
  test:
    image: "quay.io/pypa/manylinux2010_x86_64"
    command: ["./scripts/unit_test.sh"]
    working_dir: "/app"
    volumes:
      - ".:/app"

  build:
    image: "quay.io/pypa/manylinux2010_x86_64"
    command: ["./scripts/build_project.sh"]
    working_dir: "/app"
    volumes:
      - ".:/app"
