version: "3.7"
services:
  {{ cookiecutter.project_slug }}-test:
    image: "quay.io/pypa/manylinux2010_x86_64"
    command: ["/bin/bash"]
    working_dir: "/app"
    env_file:
      - .env
    volumes:
      - ".:/app"
      
  envvars:
    image: flemay/envvars
    env_file:
      - .env
    working_dir: "/work"
    volumes:
      - ".:/work"
