# Bitbucket build pipeline
image: python:3.6

pipelines:
  default:
    - step:
        caches:
          - pip

        script:
          - pip install -r requirements_dev.txt
          - pytest --cov-report=html  
